plugins {
    id 'java'
    id 'application'
}

group = 'com.seuprojeto'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Usa a versão que você baixou manualmente
    implementation 'org.json:json:20240303'
}

application {
    // Ajuste para o pacote e classe principal do seu projeto
    mainClass = 'com.cpfindex.Main'
}
