plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.14'}

group = 'com.cpfindex'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

javafx {
    version = "21"
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    implementation 'org.json:json:20240303'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'

}

application {
    mainClass = 'com.cpfindex.Main'
}



test {
    useJUnitPlatform()
}